### PR TITLE
bumping up default font size on labels and axes for readability when s…

### PR DESCRIPTION
**Pull request by ebrillhart**
This increases the default font size for labels in each component slightly in order to increase readability when chart sizes are scaled down.

### CODE REVIEW

**Comment by boygirl** [comment]
@ebrillhart why are the font sizes different for labels in the different components like line, bar etc? It makes sense to me that the tick labels and axis labels should have different sizes, but it seems like the data components should be standard.

**Comment by ebrillhart** [comment]
They were all different to begin with - except for victory axis, I just bumped all values up by one because two was a little too much. I can make them more consistent though

**Comment by boygirl** [comment]
haha, oops. Yes, please make them consistent.

**Comment by ebrillhart** [comment]
@boygirl okay, these are all consistent now! I'm making the same change to victory-pie too

**Comment by boygirl** [comment]
Approved!

**Pull request merged**
