### PR TITLE
Add `npm start` script and update README

### PR DESCRIPTION
**Pull request by coopy**
I've added standard npm scripts and updated the README to have the minimum needed to get started on development.

- `npm start` runs `builder run hot`
- `npm test` runs `builder run check`

Other:
- I've fixed the demo app - when switching between demos, the components unmount, and we need to clear the update-interval.
- I've updated the links to subcomponents in the README to not point to the deprecated repositories (but to the now-contained subcomponents).

/cc @boygirl @tptee

### CODE REVIEW

**Comment by coopy** [comment]
Fixes https://github.com/FormidableLabs/victory/issues/170

**Comment by boygirl** [comment]
Preferences for `builder run dev` vs. `builder run hot` for `npm start` alias?

**Comment by boygirl** [comment]
cc/ @coopy this looks great. Thanks for all the clean up!

**Comment by tptee** [comment]
What's the difference between `dev` and `hot` in the archetype? Does `dev` do full reloads instead?

**Comment by coopy** [comment]
Hot reloading works mostly great, and is my preference for default dev environment. `builder run dev` runs a dev server without any hot or live reloading.

**Comment by tptee** [comment]
`hot` gets my vote :+1:

**Comment by boygirl** [comment]
I'm fine with `hot` as a default

**Pull request merged**
