### PR TITLE
Error bar ecology

### PR DESCRIPTION
**Pull request by ebrillhart**
@boygirl this adds ecology docs for errorBar, and also fixes an issue that was causing labels to not attach to data. one problem is that animate doesn't seem to be working? can't pinpoint why...

### CODE REVIEW

**Comment by chilijung** [comment]
@ebrillhart I'll test it later today to check the animation part.

**Comment by chilijung** [comment]
@ebrillhart fixed! is on branch `fix/error-bar-animate`, this line break the whole thing https://github.com/FormidableLabs/victory-chart/pull/304/files#diff-515a4a90747fb9fbd388e92836b57ccdR401

**Comment by ebrillhart** [comment]
@chilijung great! that fix worked for me. I'll finish up the animate example in the docs and get this pushed up.

**Comment by ebrillhart** [comment]
@boygirl I think this is good to go if you agree

**Comment by boygirl** [comment]
@ebrillhart approved pending merge conflict resolution

**Pull request merged**
