### PR TITLE
Voronoi stack

### PR DESCRIPTION
**Pull request by stefvhuynh**
Fixes https://github.com/FormidableLabs/victory/issues/619.
Requires https://github.com/FormidableLabs/victory-core/pull/332.

Component from issue for testing:
```
render() {
    const chartProps = {
        containerComponent: <VictoryVoronoiContainer labels={(d) => d.y} />
        // containerComponent: <VictoryVoronoiContainer />
    }

    const areaProps = [
        {
            data: [
                { x: 1, y: 3 },
                { x: 2, y: 3 },
                { x: 3, y: 3 },
            ],
            // labelComponent: <VictoryTooltip />,
            // labels: (d) => d.y
        },
        {
            data: [
                { x: 1, y: 1 },
                { x: 2, y: 1 },
                { x: 3, y: 1 },
            ],
            // labelComponent: <VictoryTooltip />,
            // labels: (d) => d.y
        }
    ]

    return (
        <VictoryChart {...chartProps}>
            <VictoryStack>
                <VictoryArea {...areaProps[0]} />
                <VictoryArea {...areaProps[1]} />
            </VictoryStack>
        </VictoryChart>
    )
}
```
Toggle comments to ensure `labels` works in both cases.

### CODE REVIEW

**Comment by stefvhuynh** [comment]
There is an issue with the very last chart in the voronoi container demo. Hovering no longer highlights the bars. Chart in question:
screen shot 2018-01-19 at 4 45 47 pm

**Comment by boygirl** [comment]
More work necessary. This implementation destroys `voronoiBlacklist` functionality

**Comment by f0rr0** [comment]
@boygirl not sure if this would be related but I observed that voronoi container has some unexpected behaviour https://codesandbox.io/s/4z6ww6w7m0

**Comment by boygirl** [comment]
Depends on https://github.com/FormidableLabs/victory-core/pull/390

**Comment by boygirl** [comment]
@f0rr0 yes, that looks potentially related. The issue was that voronoi data was naive. None of the calculated data values were i.e. `_x0`, `_y0` were being used when determining the voronoi. I think that might be causing the issue you're seeing as well, but I will double check before I release this change (probably tomorrow)

**Pull request merged**
