### PR TITLE
update proptypes

### PR DESCRIPTION
**Pull request by boygirl**

### CODE REVIEW

**Comment by nfcampos** [comment]
@boygirl I don't think `flyoutProps` are actually being used anywhere... see this example https://formidable.com/open-source/victory/docs/victory-tooltip#voronoi-tooltip and add this `flyoutProps={{orientation: 'bottom'}}`, nothing changes...

**Comment by boygirl** [comment]
Thanks for catching that, @nfcampos!

**Comment by nfcampos** [comment]
(btw, why are they called `flyoutProps` if they're applied to `labelComponent`? I ended up just passing a custom `labelComponent` with props applied to it because I didn't realise that's what these were for)

**Comment by boygirl** [comment]
They're specific to `Flyout` in `VictoryTooltip`. Maybe it's not the best naming. The reason I've exposed them here instead of requiring them to be passed to labelComponent is just for convenience. Do you think `tooltipProps` is less confusing, or drop the prop all together?

**Comment by nfcampos** [comment]
`tooltipProps` would have been less confusing yes, I think, but honestly I don't really see the point of having this way of passing props to the `labelComponent` only in this component (unless there's stuff like this in other components?), because in all others I'm used to passing a custom `labelComponent` or `dataComponent` if I want to pass props to it

**Comment by boygirl** [comment]
Yes, point taken. It doesn't match the others. I'll nuke it.

**Pull request merged**
