### PR TITLE
Use static propTypes/defaultProps syntax so the component signature is at the top

### PR DESCRIPTION
**Pull request by exogen**
/cc @boygirl @colinmegill

### CODE REVIEW

**Comment by boygirl** [comment]
cc/ @exogen the checks are all passing on this branch for me locally. Travis! Damn your eyes! Approved

**Comment by exogen** [comment]
Weird, they pass for me locally too. I'll investigate why Travis is mad

**Comment by exogen** [comment]
Ah, I'm guessing it's because in webpack.config.coverage.js, we use `isparta?{ babel: { stage: 1 } }` instead of stage 0 like everywhere else. I'm on it.

**Comment by exogen** [comment]
Looks like that fixed it!

**Comment by boygirl** [comment]
Approved!

**Pull request merged**
