### PR TITLE
Moves label text to props rather than children

### PR DESCRIPTION
**Pull request by cpb**
Depends on FormidableLabs/victory-core#10 We were previously assuming
that the children of custom labels contained accurate label information.
However, as discussed in FormidableLabs/victory-chart#101 we are moving
to an api that supports making many clones of a single custom label
component based on an array of label values. That use case is clear in
not assuming that the children of the label 'factory' already know the
label text, it can't, we want to explicitly provide it.

So, I am proposing we eschew handling of injected components children.
Instead, we will provide our best guess at label text as a prop.

### CODE REVIEW

**Comment by boygirl** [comment]
@cpb https://github.com/FormidableLabs/victory-core/pull/10 is merged and released as `v1.0.0`

**Comment by cpb** [comment]
OK great, I'll update that dependency!

**Comment by cpb** [comment]
:+1:

**Comment by boygirl** [comment]
@cpb I think this change needs to happen in victory-axis too.

**Comment by cpb** [comment]
- [ ] Don't leave victory-axis behind!

**Comment by cpb** [comment]
:+1:

**Comment by boygirl** [comment]
cc/ @cpb this is _almost_ done. I think tick labels in `tick.jsx` are still getting label text via children rather than a text prop. Other than that, approved!

**Comment by boygirl** [comment]
cc/ @cpb I replaced the couple missing instances of using label children with using the `text` prop. Depends on https://github.com/FormidableLabs/victory-core/pull/21 for feature parity.

**Comment by cpb** [comment]
Thanks @boygirl I appreciate you picking this up. Forgot about the tick!

**Pull request merged**
