### PR TITLE
Replicate victory-bar docs change

### PR DESCRIPTION
**Pull request by exogen**
/cc @david-davidson @boygirl

### CODE REVIEW

**Comment by boygirl** [comment]
:+1:

**Comment by david-davidson** [comment]
@exogen Nice, thanks!

**Comment by boygirl** [comment]
What the hell travis? I think this is probably the same eslint bug

**Comment by exogen** [comment]
@boygirl Yeah, same thing happening on `master`. It's actually using an old `0.x` version of `eslint` though, not the latest version, but I bet it's still related to bad versions.

**Comment by david-davidson** [comment]
@boygirl @exogen Rebased on top of master (w/ `builder`, etc.), and CI is looking good :+1: -- gonna merge this.

@boygirl, I know Victory's build world has been moving quickly this last week--is there anything blocking an npm patch release with this? (With the proper release workflow this time. :smile: ) We're up to date with the `builder 2.1.1` npm fix; just want to make sure there isn't something else in flux I might be forgetting.

**Comment by boygirl** [comment]
@david-davidson I'll double check in the morning and do a release if nothing is blocking

**Comment by david-davidson** [comment]
:ok_hand: If it ends up that there's nothing blocking, `victory-axis` and `victory-pie` are in the same merged-but-not-yet-published state.

**Pull request merged**
