### PR TITLE
Handle empty data array or single data point

### PR DESCRIPTION
**Pull request by ebrillhart**
This allows all chart components to handle either an empty data array or a single data point. One aspect of weirdness I'm getting right now is that line is handling having a single data point fine in that nothing breaks and the label is where it's supposed to be (and the dataset generates properly)... but the line just doesn't show up. Thoughts?

@boygirl 

addresses https://github.com/FormidableLabs/victory/issues/191

### CODE REVIEW

**Comment by boygirl** [comment]
@ebrillhart line _shouldn't_ work with a single datapoint because you need two points minimum to draw a line. I don' think there's anything we can do about this edge case.

**Comment by ebrillhart** [comment]
@boygirl yeah, but I was trying to handle that by having it use generateData and give a warning, which worked great for area... but yeah it might just be weird.

**Comment by boygirl** [comment]
What data are you adding? just pushing `(0, 0)` onto the dataset?

**Comment by ebrillhart** [comment]
@boygirl no, I'm trying to just have it handle it the same as it would if absolutely no data prop was added

**Comment by ebrillhart** [comment]
@boygirl and all of the stuff does, like where the label ends up makes sense for the data that's generated... but the line itself just doesn't show

**Comment by boygirl** [comment]
As in using default data? I don't think that's appropriate for empty and single point data states. I'm imagining this state coming about from filtering a dataset or something. You don't _want_ it to show any data

**Comment by ebrillhart** [comment]
@boygirl this should handle stuff in the desired way now

**Comment by boygirl** [comment]
@ebrillhart looks good! Approved.

**Comment by MiLeung** [comment]
I'm getting the following error when passing an empty array to the data prop of VictoryLine in Victory Native:

"Warning: Failed prop type: The prop `d` is marked as required in `Path`, but its value is `null`."

Is this as intended? I think a warning saying that a line will not be rendered would be more appropriate.

**Pull request merged**
