### PR TITLE
allow styled labels in VictoryGroup

### PR DESCRIPTION
**Pull request by boygirl**
add a check so that `VictoryGroup` does not attempt to merge styles for `VictoryLabel` children

### CODE REVIEW

**Comment by camsjams** [comment]
Thanks @boygirl !

**Comment by camsjams** [comment]
Will this be on npm soon?

**Comment by boygirl** [comment]
I'm doing a release today :)

**Comment by camsjams** [comment]
Great - thanks!

**Comment by camsjams** [comment]
Wow amazing fix! thanks again

**Pull request merged**
